Repository laminas/getlaminas.org, pull requests merged in 2022-08, with the labels that each got.

#107 Removed unused `laminas/laminas-dependency-plugin`
  composer.json
  composer.lock
Labels: Enhancement, Dependencies

#110 CVP: Apidemia
  config/autoload/commercial-vendors.global.php
  public/images/vendors/apidemia.png
Labels: Enhancement

#111 Adds missing container for grid with logos to prevent negative margins
  templates/app/home-page.phtml
Labels: Bug

#113 Add psalm to CI pipeline
  composer.json
  composer.lock
  psalm-baseline.xml
  psalm.xml.dist
  src/App/AbstractCollection.php
  src/App/AccessLoggerFactory.php
  src/App/EventDispatcherFactory.php
  src/App/FrontMatter/Document.php
  src/App/Handler/CommercialVendorsHandlerFactory.php
  src/App/Handler/HomePageHandlerFactory.php
  src/App/Handler/StaticPageHandlerFactory.php
  src/App/LoggingErrorListenerDelegator.php
  src/App/Template/InjectAssetRevisionsDelegator.php
  src/Blog/ConfigProvider.php
  src/Blog/Console/FeedGenerator.php
  src/Blog/Console/FeedGeneratorFactory.php
  src/Blog/Console/GenerateSearchData.php
  src/Blog/Console/MarkdownFileFilter.php
  src/Blog/Console/RoutesTrait.php
  src/Blog/Console/SeedBlogDatabase.php
  src/Blog/CreateBlogPostFromDataArray.php
  src/Blog/Handler/DisplayPostHandler.php
  src/Blog/Handler/DisplayPostHandlerFactory.php
  src/Blog/Handler/FeedHandlerFactory.php
  src/Blog/Handler/ListPostsHandler.php
  src/Blog/Handler/ListPostsHandlerFactory.php
  src/Blog/Handler/SearchHandler.php
  src/Blog/Handler/SearchHandlerFactory.php
  src/Blog/Listener/FetchBlogPostEventListenersDelegator.php
  src/Blog/Listener/FetchBlogPostFromMapperListenerFactory.php
  src/Blog/Mapper/MapperFactory.php
  src/Blog/Mapper/MapperInterface.php
  src/Blog/Mapper/PdoMapper.php
  src/Blog/Mapper/PdoPaginator.php
  src/Blog/PlatesFunctionsDelegator.php
  src/ReleaseFeed/DisplayFeedHandlerFactory.php
  src/ReleaseFeed/ReceiveFeedItemHandler.php
  src/ReleaseFeed/ReceiveFeedItemHandlerFactory.php
  src/ReleaseFeed/Releases.php
  src/ReleaseFeed/VerifyTokenMiddlewareFactory.php
  src/Security/Handler/AdvisoryHandlerFactory.php
  src/Security/Handler/SecurityHandler.php
  src/Security/Handler/SecurityHandlerFactory.php
Labels: Enhancement
